name: Build and Test
on:
  push:
    branches:
      - develop
      - master
jobs:
  build-app:
    runs-on: [ubuntu-latest]
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      
      - name: Check out source code
        uses: actions/checkout@v1

      - name: Install dependencies
        run: go get -d -t ./...  

      - name: Build
        run: go build .
      
      - name: Test
        run: go test -v .
      
      - name: Build Docker image
        run: docker build -t molly-lucky/dog-park:develop .

      - name: Authenticate Docker with ECR
        uses: actions/aws/cli@master
        with:
          args: ecr get-login --region=ca-central-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Push Docker image to ECR
        run: docker push molly-lucky/dog-park:${GITHUB_REF##*/}