name: Build and Test
on:
  push:
    branches:
      - develop
      - master
jobs:
  build-app:
    runs-on: [ubuntu-latest]
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      
      - name: Check out source code
        uses: actions/checkout@v1

      - name: Install dependencies
        run: go get -d -t ./...  

      - name: Build
        run: go build .
      
      - name: Test
        run: go test -v .
      
      - name: Build Docker image
        run: docker build --tag dogpark:develop .

      - name: Push to ECR
        id: ecr
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ca-central-1
          image: dogpark:develop
